MODEL:
  META_ARCHITECTURE: "AdaptionRCNN"
  WEIGHT: "CHANGE/ME"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 201
  DENSITY_HEAD:
    NUM_CLASSES: 17
    FPN_LEVEL: 1
    FPN_LEVEL_STRIDE: 0.125
  HEATMAP_ON: True
DATASETS:
  TRAIN: ("rpc_2019_train_render_density_map",)
  TEST: ("rpc_2019_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  ASPECT_RATIO_GROUPING: False
  NUM_WORKERS: 12
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (70000, 100000, 120000)
  MAX_ITER: 140000
  CROSS_TRAIN_STEPS: 14
  ITER_PER_STEP: 10000
  IMS_PER_BATCH: 8
TEST:
  IMS_PER_BATCH: 8
  GENERATE_PSEUDO_LABELS: True
  PSEUDO_LABELS_ANN_FILE: '/data7/lufficc/projects/DPNet/work_dirs/rpc_2019_train_render_density_map_17/inference/rpc_2019_test/pseudo_labeling.json'

OUTPUT_DIR: 'work_dirs/rpc_2019_train_render_density_map_cross_finetune_17'